.TH ONESIXTYONE "1" "2010-10-18" "onesixtyone 0.3.2" "User Commands"
.SH NAME
onesixtyone \- an efficient SNMP scanner
.SH SYNOPSIS
.B onesixtyone
.RI "[" "options ..." "] " host " [" community "]"
.SH DESCRIPTION
.\" Add any additional description here
.B onesixtyone
is a network scanner that sends an
.SM SNMP
request for the
.\" sysDescr.0 = 1.3.6.1.2.1.1.1.0
system.sysDescr.0 value, present on almost all
.SM SNMP
enabled devices,
and logs the returned value, which should be a description of the
system software running on the device.
.PP
Requests are sent to hosts as fast as possible, rather than waiting
for each one to respond individually, and responses are displayed as
they are received. By default,
.B onesixtyone
waits for 10 milliseconds between sending packets.
.PP
After all packets have been sent,
.B onesixtyone
will wait for five seconds for outstanding responses.
.PP
Hosts can be specified as IP addresses or using CIDR notation to target
all hosts on a particular subnet; no name lookup is done. For example,
127.0.0.1 will scan one host, and 192.168.0.0/24 will scan all hosts
from 192.168.0.1 to 192.168.0.254.
.SH OPTIONS
.IP "-c community-file"
Try the community names from the supplied file instead of the default
communities of "public" and "private".
.I community-file
should have one
community name per line.
.IP "-i host-file"
Read target hosts from a file. Hosts should be separated by white
space or newlines. If host-file is "-", hosts will be read from stdin.
.IP "-o output-file"
Send responses to file. They will also go to stdout unless you use -q.
.IP -d
Enables debug mode. Use twice for more per-packet information.
.IP "-w n"
Wait
.I n
milliseconds between sending packets.
The default delay is 10 milliseconds. If 0 is requested, packets will be
sent as fast as possible.
.IP -q
Quiet mode. Do not print log to stdout, use with -o.
.SH EXAMPLES
...waiting...
.\" this section for Fedora only
.SH FILES
.I /usr/share/onesixtyone/dict.txt
.RS
A list of sample community names.
.RE
.SH AUTHOR
Written by Solar Eclipse, solareclipse at phreedom dot org.
